name: inknhue
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pytorch-cuda=11.8
  - pip:
      - opencv-contrib-python>=4.1.0.25
      - tensorflow>=2.12.0
      - gradio>=3.20.1
      - scikit-learn>=0.23.1
      - scikit-image>=0.14.5
      - tqdm
      - numpy<1.24
      - rich
      - matplotlib
      - einops
      - Pillow
      - accelerate
      - omegaconf
      - wandb
      - huggingface-hub
      - taming-transformers
